### ISSUE TITLE
Pilot configuration setup: differentiate access point role (C2/C3) from corporate (C1/C4)

### ISSUE THREAD

**Issue by mgilis** [BPC-Exchange-Framework/BPC-Market-Pilot#2]
As in Wave1 phase, access point ‘emulate’ corporates when exchanging documents, the flow is not representative. So to differentiate, we should allow a different id for C1/C4 even it is a test without having an actual corporate involved.

**Comment by brittahollandwork** [comment]
Resolution: The SC voted on 6/7 to **allow** a different id for C1/C4s even if it's a test without having a corporate involved.
