### ISSUE TITLE
Message orchestration: application response 

### ISSUE THREAD

**Issue by mgilis** [BPC-Exchange-Framework/BPC-Market-Pilot#4]
Currently only rejects are supported. However, for transparency we propose also accept messages should be implemented. This then to implement ‘guaranteed delivery’ feature, avoiding queries to the different parties involved on the invoice status

**Comment by brittahollandwork** [comment]
Technical Committee Response 5/31: @mgilis Clarification needed - does this refer to the corner 3 response, or corner 4 response? For corner 3, the AS4 transport level response acknowledges receipt of the message.

**Comment by mgilis** [comment]
Follow up from Michel: Corner 3 sends message to Corner 2 that document has been received by Corner 4 (and therefore is valid)., 
Please read s: Corner 3 sends message to Corner 2 that document has been delivered to Corner 3 (and therefore the C2->C3 document exchange can be flagged as OK / finished).

**Comment by eelamont76** [comment]
The IOC's PRG  subcommittee suggests that this requirement be fulfilled via Service Level Agreements defined for a response from Corner 3.

**Comment by brittahollandwork** [comment]
The IOC's PRG recommended that optional corner 4 receipt (acknowledgement that the document has been received) be implemented. This will be socialized with the IOC at the meeting on 6/23/22 and presented back to the TC on 6/27/22.

**Comment by brittahollandwork** [comment]
The Technical Committee approved the Receipt Acknowledgement Profile for IOC review on 8/9/22 - thus resolving the originally documented issue.
