### ISSUE TITLE
New Document Types for Remittance 

### ISSUE THREAD

**Issue by eelamont76** [BPC-Exchange-Framework/BPC-Market-Pilot#9]
The Remittance Work Group has determined the need for three remittance document types available for SMP entries during the validation phase testing and are seeking TC guidance on what (if any) specification updates are needed to accommodate these documents:

ISO 20022 core remittance
ISO 20022 remittance with line items
EDI 820 remittance

**Comment by brittahollandwork** [comment]
No updates are needed. These document types are not defined within the SMP specification.
